name: ManhuntCore
version: 1.0
main: com.jackchapman.manhuntcore.ManhuntCore
api-version: 1.16
description: The core plugin for the manhunt gamemode

commands:
  forcestart:
    description: Forcefully starts the current game
    usage: /<command>
  givetracker:
    description: Gives the player a tracking item
    usage: /<command>

permissions:
  core.forcestart:
    description: Allows the player to forcefully start a game
    default: op
  core.givetracker:
    description: Allows the player to give custom tracker items to others
    default: op
  core.compass+:
    description: Gives the player a more advanced compass at the beginning of the game
    default: op
